//! Kubernetes API маршруты
//!
//! ~720 строк маршрутов Kubernetes API

use crate::api::handlers;
use crate::api::state::AppState;
use axum::{
    routing::{delete, get, post, put},
    Router,
};
use std::sync::Arc;

/// Создаёт маршруты Kubernetes API
pub fn kubernetes_routes() -> Router<Arc<AppState>> {
    Router::new()
        // ── Kubernetes API ──────────────────────────────────────────────────
        // Cluster info
        .route(
            "/api/kubernetes/cluster/info",
            get(handlers::get_cluster_info),
        )
        .route(
            "/api/kubernetes/cluster/nodes",
            get(handlers::get_cluster_nodes),
        )
        .route(
            "/api/kubernetes/cluster/summary",
            get(handlers::get_k8s_cluster_summary),
        )
        // Health
        .route("/api/kubernetes/health", get(handlers::kubernetes_health))
        .route(
            "/api/kubernetes/health/detailed",
            get(handlers::kubernetes_health_detailed),
        )
        // Namespaces
        .route("/api/kubernetes/namespaces", get(handlers::list_namespaces))
        .route(
            "/api/kubernetes/namespaces/{name}",
            get(handlers::get_namespace),
        )
        .route(
            "/api/kubernetes/namespaces",
            post(handlers::create_namespace),
        )
        .route(
            "/api/kubernetes/namespaces/{name}",
            put(handlers::update_namespace),
        )
        .route(
            "/api/kubernetes/namespaces/{name}",
            delete(handlers::delete_namespace),
        )
        .route(
            "/api/kubernetes/namespaces/{name}/quota",
            get(handlers::get_namespace_quota),
        )
        .route(
            "/api/kubernetes/namespaces/{name}/limits",
            get(handlers::get_namespace_limits),
        )
        // Services
        .route("/api/kubernetes/services", get(handlers::list_services))
        .route(
            "/api/kubernetes/namespaces/{namespace}/services",
            post(handlers::create_service),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/services/{name}",
            get(handlers::get_service),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/services/{name}",
            put(handlers::update_service),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/services/{name}",
            delete(handlers::delete_service),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/services/{name}/endpoints",
            get(handlers::get_service_endpoints),
        )
        // Ingress & IngressClass
        .route("/api/kubernetes/ingresses", get(handlers::list_ingresses))
        .route(
            "/api/kubernetes/namespaces/{namespace}/ingresses",
            post(handlers::create_ingress),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/ingresses/{name}",
            get(handlers::get_ingress),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/ingresses/{name}",
            put(handlers::update_ingress),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/ingresses/{name}",
            delete(handlers::delete_ingress),
        )
        .route(
            "/api/kubernetes/ingressclasses",
            get(handlers::list_ingress_classes),
        )
        .route(
            "/api/kubernetes/ingressclasses/{name}",
            get(handlers::get_ingress_class),
        )
        // ConfigMaps
        .route("/api/kubernetes/configmaps", get(handlers::list_configmaps))
        .route(
            "/api/kubernetes/namespaces/{namespace}/configmaps",
            post(handlers::create_configmap),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/configmaps/{name}",
            get(handlers::get_configmap),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/configmaps/{name}",
            put(handlers::update_configmap),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/configmaps/{name}",
            delete(handlers::delete_configmap),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/configmaps/{name}/yaml",
            get(handlers::get_configmap_yaml),
        )
        .route(
            "/api/kubernetes/configmaps/validate",
            post(handlers::validate_configmap),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/configmaps/{name}/references",
            get(handlers::get_configmap_references),
        )
        // Secrets
        .route("/api/kubernetes/secrets", get(handlers::list_secrets))
        .route(
            "/api/kubernetes/namespaces/{namespace}/secrets",
            post(handlers::create_secret),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/secrets/{name}",
            get(handlers::get_secret),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/secrets/{name}",
            put(handlers::update_secret),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/secrets/{name}",
            delete(handlers::delete_secret),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/secrets/{name}/reveal",
            get(handlers::reveal_secret),
        )
        // NetworkPolicy
        .route(
            "/api/kubernetes/networkpolicies",
            get(handlers::list_networkpolicies),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/networkpolicies",
            post(handlers::create_networkpolicy),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/networkpolicies/{name}",
            get(handlers::get_networkpolicy),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/networkpolicies/{name}",
            put(handlers::update_networkpolicy),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/networkpolicies/{name}",
            delete(handlers::delete_networkpolicy),
        )
        // Gateway API (optional, read-only)
        .route(
            "/api/kubernetes/gateway-api/status",
            get(handlers::get_gateway_api_status),
        )
        .route("/api/kubernetes/gateways", get(handlers::list_gateways))
        .route("/api/kubernetes/httproutes", get(handlers::list_httproutes))
        .route("/api/kubernetes/grpcroutes", get(handlers::list_grpcroutes))
        // RBAC UX
        .route(
            "/api/kubernetes/rbac/check",
            post(handlers::check_kubernetes_rbac),
        )
        .route(
            "/api/kubernetes/rbac/rules-review",
            post(handlers::post_self_subject_rules_review),
        )
        .route(
            "/api/kubernetes/namespaces/{name}/pod-security",
            get(handlers::get_namespace_pod_security),
        )
        .route(
            "/api/kubernetes/namespaces/{name}/pod-security",
            put(handlers::put_namespace_pod_security),
        )
        // ServiceAccounts & RBAC objects
        .route(
            "/api/kubernetes/serviceaccounts",
            get(handlers::list_service_accounts),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/serviceaccounts",
            post(handlers::create_service_account),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/serviceaccounts/{name}",
            get(handlers::get_service_account),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/serviceaccounts/{name}",
            delete(handlers::delete_service_account),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/serviceaccounts/{name}/secrets",
            get(handlers::list_service_account_secrets),
        )
        .route("/api/kubernetes/roles", get(handlers::list_roles))
        .route(
            "/api/kubernetes/namespaces/{namespace}/roles",
            post(handlers::create_role),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/roles/{name}",
            get(handlers::get_role),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/roles/{name}",
            put(handlers::update_role),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/roles/{name}",
            delete(handlers::delete_role),
        )
        .route(
            "/api/kubernetes/rolebindings",
            get(handlers::list_role_bindings),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/rolebindings",
            post(handlers::create_role_binding),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/rolebindings/{name}",
            get(handlers::get_role_binding),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/rolebindings/{name}",
            put(handlers::update_role_binding),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/rolebindings/{name}",
            delete(handlers::delete_role_binding),
        )
        .route(
            "/api/kubernetes/clusterroles",
            get(handlers::list_cluster_roles),
        )
        .route(
            "/api/kubernetes/clusterroles",
            post(handlers::create_cluster_role),
        )
        .route(
            "/api/kubernetes/clusterroles/{name}",
            get(handlers::get_cluster_role),
        )
        .route(
            "/api/kubernetes/clusterroles/{name}",
            put(handlers::update_cluster_role),
        )
        .route(
            "/api/kubernetes/clusterroles/{name}",
            delete(handlers::delete_cluster_role),
        )
        .route(
            "/api/kubernetes/clusterrolebindings",
            get(handlers::list_cluster_role_bindings),
        )
        .route(
            "/api/kubernetes/clusterrolebindings",
            post(handlers::create_cluster_role_binding),
        )
        .route(
            "/api/kubernetes/clusterrolebindings/{name}",
            get(handlers::get_cluster_role_binding),
        )
        .route(
            "/api/kubernetes/clusterrolebindings/{name}",
            put(handlers::update_cluster_role_binding),
        )
        .route(
            "/api/kubernetes/clusterrolebindings/{name}",
            delete(handlers::delete_cluster_role_binding),
        )
        // Storage: PV/PVC/StorageClass
        .route(
            "/api/kubernetes/persistentvolumes",
            get(handlers::list_persistent_volumes),
        )
        .route(
            "/api/kubernetes/persistentvolumes",
            post(handlers::create_persistent_volume),
        )
        .route(
            "/api/kubernetes/persistentvolumes/{name}",
            get(handlers::get_persistent_volume),
        )
        .route(
            "/api/kubernetes/persistentvolumes/{name}",
            delete(handlers::delete_persistent_volume),
        )
        .route(
            "/api/kubernetes/persistentvolumeclaims",
            get(handlers::list_persistent_volume_claims),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/persistentvolumeclaims",
            post(handlers::create_persistent_volume_claim),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/persistentvolumeclaims/{name}",
            get(handlers::get_persistent_volume_claim),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/persistentvolumeclaims/{name}",
            put(handlers::update_persistent_volume_claim),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/persistentvolumeclaims/{name}",
            delete(handlers::delete_persistent_volume_claim),
        )
        .route(
            "/api/kubernetes/storageclasses",
            get(handlers::list_storage_classes),
        )
        .route(
            "/api/kubernetes/storageclasses",
            post(handlers::create_storage_class),
        )
        .route(
            "/api/kubernetes/storageclasses/{name}",
            get(handlers::get_storage_class),
        )
        .route(
            "/api/kubernetes/storageclasses/{name}",
            delete(handlers::delete_storage_class),
        )
        // CSI snapshots (optional, read-only)
        .route(
            "/api/kubernetes/snapshots/status",
            get(handlers::get_snapshot_api_status),
        )
        .route(
            "/api/kubernetes/volumesnapshots",
            get(handlers::list_volume_snapshots),
        )
        .route(
            "/api/kubernetes/volumesnapshotclasses",
            get(handlers::list_volume_snapshot_classes),
        )
        // CSI details (optional, read-only)
        .route(
            "/api/kubernetes/csi/status",
            get(handlers::get_csi_api_status),
        )
        .route(
            "/api/kubernetes/csidrivers",
            get(handlers::list_csi_drivers),
        )
        .route("/api/kubernetes/csinodes", get(handlers::list_csi_nodes))
        .route(
            "/api/kubernetes/volumeattachments",
            get(handlers::list_volume_attachments),
        )
        // Batch & scheduling
        .route("/api/kubernetes/jobs", get(handlers::list_jobs))
        .route(
            "/api/kubernetes/namespaces/{namespace}/jobs",
            post(handlers::create_job),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/jobs/{name}",
            get(handlers::get_job),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/jobs/{name}",
            delete(handlers::delete_job),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/jobs/{name}/pods",
            get(handlers::list_job_pods),
        )
        .route("/api/kubernetes/cronjobs", get(handlers::list_cronjobs))
        .route(
            "/api/kubernetes/namespaces/{namespace}/cronjobs",
            post(handlers::create_cronjob),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/cronjobs/{name}",
            get(handlers::get_cronjob),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/cronjobs/{name}",
            delete(handlers::delete_cronjob),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/cronjobs/{name}/suspend/{suspend}",
            put(handlers::update_cronjob_suspend),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/cronjobs/{name}/history",
            get(handlers::list_cronjob_history),
        )
        .route(
            "/api/kubernetes/priorityclasses",
            get(handlers::list_priority_classes),
        )
        .route(
            "/api/kubernetes/priorityclasses",
            post(handlers::create_priority_class),
        )
        .route(
            "/api/kubernetes/priorityclasses/{name}",
            delete(handlers::delete_priority_class),
        )
        .route(
            "/api/kubernetes/poddisruptionbudgets",
            get(handlers::list_pdbs),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/poddisruptionbudgets",
            post(handlers::create_pdb),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/poddisruptionbudgets/{name}",
            delete(handlers::delete_pdb),
        )
        // Advanced: HPA, quota, limits, CRD, dynamic CR, VPA
        .route(
            "/api/kubernetes/horizontalpodautoscalers",
            get(handlers::list_hpas),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/horizontalpodautoscalers",
            post(handlers::create_hpa),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/horizontalpodautoscalers/{name}",
            get(handlers::get_hpa),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/horizontalpodautoscalers/{name}",
            put(handlers::update_hpa),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/horizontalpodautoscalers/{name}",
            delete(handlers::delete_hpa),
        )
        .route(
            "/api/kubernetes/resourcequotas",
            get(handlers::list_resource_quotas),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/resourcequotas",
            post(handlers::create_resource_quota),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/resourcequotas/{name}",
            get(handlers::get_resource_quota),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/resourcequotas/{name}",
            put(handlers::update_resource_quota),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/resourcequotas/{name}",
            delete(handlers::delete_resource_quota),
        )
        .route(
            "/api/kubernetes/limitranges",
            get(handlers::list_limit_ranges),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/limitranges",
            post(handlers::create_limit_range),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/limitranges/{name}",
            get(handlers::get_limit_range),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/limitranges/{name}",
            put(handlers::update_limit_range),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/limitranges/{name}",
            delete(handlers::delete_limit_range),
        )
        .route(
            "/api/kubernetes/customresourcedefinitions",
            get(handlers::list_crds),
        )
        .route(
            "/api/kubernetes/customresourcedefinitions/{name}",
            get(handlers::get_crd),
        )
        .route(
            "/api/kubernetes/customobjects",
            get(handlers::list_custom_objects).post(handlers::create_custom_object_query),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/customobjects/{plural}/{name}",
            get(handlers::get_custom_object),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/customobjects/{plural}/{name}",
            put(handlers::replace_custom_object),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/customobjects/{plural}/{name}",
            delete(handlers::delete_custom_object),
        )
        .route(
            "/api/kubernetes/cluster/customobjects/{plural}/{name}",
            get(handlers::get_custom_object_cluster),
        )
        .route(
            "/api/kubernetes/cluster/customobjects/{plural}/{name}",
            put(handlers::replace_custom_object_cluster),
        )
        .route(
            "/api/kubernetes/cluster/customobjects/{plural}/{name}",
            delete(handlers::delete_custom_object_cluster),
        )
        .route(
            "/api/kubernetes/cluster/customobjects/{plural}",
            post(handlers::create_custom_object_cluster),
        )
        .route("/api/kubernetes/vpa/status", get(handlers::get_vpa_status))
        .route(
            "/api/kubernetes/verticalpodautoscalers",
            get(handlers::list_vertical_pod_autoscalers),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/verticalpodautoscalers/{name}",
            get(handlers::get_vertical_pod_autoscaler),
        )
        // Observability: Events & Metrics
        .route(
            "/api/kubernetes/events",
            get(handlers::list_events),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/events",
            get(handlers::list_events),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/events/{name}",
            get(handlers::get_event),
        )
        // Events WebSocket Streaming
        .route(
            "/api/kubernetes/namespaces/{namespace}/events/stream",
            get(handlers::events_websocket),
        )
        // Troubleshooting Dashboard
        .route(
            "/api/kubernetes/troubleshoot",
            get(handlers::get_troubleshooting_report),
        )
        // Kubernetes Runbook Integration
        .route(
            "/api/kubernetes/runbooks",
            get(handlers::get_available_runbooks),
        )
        .route(
            "/api/kubernetes/runbooks/execute",
            post(handlers::execute_runbook),
        )
        .route(
            "/api/kubernetes/runbooks/{task_id}/status",
            get(handlers::get_runbook_status),
        )
        // Prometheus Metrics Integration
        .route(
            "/api/kubernetes/prometheus/metrics",
            get(handlers::get_prometheus_metrics),
        )
        .route(
            "/api/kubernetes/prometheus/health",
            get(handlers::check_prometheus_health),
        )
        // Kubernetes Inventory Sync
        .route(
            "/api/kubernetes/inventory/sync/preview",
            get(handlers::get_inventory_sync_preview),
        )
        .route(
            "/api/kubernetes/inventory/sync",
            post(handlers::execute_inventory_sync),
        )
        // Kubernetes Pods
        .route(
            "/api/kubernetes/pods",
            get(handlers::list_pods),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/pods",
            get(handlers::list_pods),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/pods/{name}",
            get(handlers::get_pod),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/pods/{name}",
            delete(handlers::delete_pod),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/pods/{name}/restart",
            post(handlers::restart_pod),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/pods/{name}/logs",
            get(handlers::get_pod_logs),
        )
        .route(
            "/api/kubernetes/metrics/pods",
            get(handlers::list_pod_metrics),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/metrics/pods",
            get(handlers::list_pod_metrics),
        )
        .route(
            "/api/kubernetes/namespaces/{namespace}/metrics/pods/{name}",
            get(handlers::get_pod_metrics),
        )
        .route(
            "/api/kubernetes/metrics/nodes",
            get(handlers::list_node_metrics),
        )
        .route(
            "/api/kubernetes/metrics/nodes/{name}",
            get(handlers::get_node_metrics),
        )
        .route(
            "/api/kubernetes/metrics/top/pods",
            get(handlers::get_top_pods),
        )
        .route(
            "/api/kubernetes/metrics/top/nodes",
            get(handlers::get_top_nodes),
        )
        .route(
            "/api/kubernetes/topology",
            get(handlers::get_topology),
        )
        // Helm
        .route(
            "/api/kubernetes/helm/repos",
            get(handlers::list_helm_repos),
        )
        .route(
            "/api/kubernetes/helm/repos",
            post(handlers::add_helm_repo),
        )
        .route(
            "/api/kubernetes/helm/charts",
            get(handlers::search_helm_charts),
        )
        .route(
            "/api/kubernetes/helm/charts/{repo}/{chart}",
            get(handlers::get_helm_chart),
        )
        .route(
            "/api/kubernetes/helm/releases",
            get(handlers::list_helm_releases),
        )
        .route(
            "/api/kubernetes/helm/releases",
            post(handlers::install_helm_chart),
        )
        .route(
            "/api/kubernetes/helm/releases/{namespace}/{name}",
            get(handlers::get_helm_release_history),
        )
        .route(
            "/api/kubernetes/helm/releases/{namespace}/{name}",
            put(handlers::upgrade_helm_release),
        )
        .route(
            "/api/kubernetes/helm/releases/{namespace}/{name}/rollback",
            post(handlers::rollback_helm_release),
        )
        .route(
            "/api/kubernetes/helm/releases/{namespace}/{name}",
            delete(handlers::uninstall_helm_release),
        )
        .route(
            "/api/kubernetes/helm/releases/{namespace}/{name}/values",
            get(handlers::get_helm_release_values),
        )
        .route(
            "/api/kubernetes/helm/releases/{namespace}/{name}/values",
            put(handlers::update_helm_release_values),
        )
        // Multi-Cluster Management
        .route(
            "/api/kubernetes/clusters",
            get(handlers::list_kubernetes_clusters),
        )
        .route(
            "/api/kubernetes/clusters",
            post(handlers::add_kubernetes_cluster),
        )
        .route(
            "/api/kubernetes/clusters/{name}",
            post(handlers::switch_kubernetes_cluster),
        )
        .route(
            "/api/kubernetes/clusters/{name}",
            delete(handlers::remove_kubernetes_cluster),
        )
        .route(
            "/api/kubernetes/cluster/health",
            get(handlers::get_cluster_health),
        )
        .route(
            "/api/kubernetes/cluster/aggregate",
            get(handlers::get_aggregate_view),
        )
}
