version: "3.4"

services:
  runner:
    image: docker.io/tnl-o/runner:${VELUM_VERSION:-latest}
    restart: always
    environment:
      VELUM_WEB_ROOT: ${VELUM_WEB_ROOT:-http://server:3000}
      VELUM_RUNNER_API_URL: ${VELUM_RUNNER_API_URL:-http://server:3000/internal}
      VELUM_RUNNER_REGISTRATION_TOKEN: ${VELUM_RUNNER_REGISTRATION_TOKEN:-H1wDyorbg6gTSwJlVwle2Fne}

  server:
    environment:
      VELUM_RUNNER_REGISTRATION_TOKEN: ${VELUM_RUNNER_REGISTRATION_TOKEN:-H1wDyorbg6gTSwJlVwle2Fne}
